swagger: "2.0"
info:
  title: Documentation de l'API Argent-Bank
  description: Contient tous les points de terminaison (endpoints) disponibles dans cette base de code.
  version: "1.0.0"
  termsOfService: "http://swagger.io/terms/"
host: localhost:3001
basePath: /api/v1
schemes:
  - http

paths:
  /user/login:
    post:
      tags:
        - Module Utilisateur
      summary: Connexion
      description: API pour se connecter
      parameters:
        - in: body
          name: body
          description: Données de connexion
          required: true
          schema:
            $ref: "#/definitions/Login"
      produces:
        - application/json
      responses:
        "200":
          description: Connexion réussie
          schema:
            $ref: "#/definitions/LoginResponse"
        "400":
          description: Champs invalides
        "500":
          description: Erreur serveur interne

  /user/signup:
    post:
      tags:
        - Module Utilisateur
      summary: Inscription
      description: API pour s'inscrire
      parameters:
        - in: body
          name: body
          description: Données d'inscription
          required: true
          schema:
            $ref: "#/definitions/User"
      produces:
        - application/json
      responses:
        "200":
          description: Inscription réussie
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Champs invalides
        "500":
          description: Erreur serveur interne

  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - Module Utilisateur
      summary: Profil utilisateur
      description: API pour récupérer le profil utilisateur
      parameters:
        - in: header
          name: Authorization
          description: Joindre le token JWT Bearer
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: Profil utilisateur récupéré avec succès
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Champs invalides
        "500":
          description: Erreur serveur interne

    put:
      security:
        - Bearer: []
      tags:
        - Module Utilisateur
      summary: Mettre à jour le profil utilisateur
      description: API pour mettre à jour le profil utilisateur
      parameters:
        - in: header
          name: Authorization
          description: Joindre le token JWT Bearer
          required: true
          type: string
        - in: body
          name: body
          description: Attributs à mettre à jour dans le profil utilisateur
          required: true
          schema:
            $ref: "#/definitions/UserProfile"
      produces:
        - application/json
      responses:
        "200":
          description: Profil utilisateur mis à jour avec succès
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Champs invalides
        "500":
          description: Erreur serveur interne
